version: '3.1'

services:
  api:
    build: 
      context: .
      dockerfile: Api.Dockerfile
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      dockerfile: Web.Dockerfile
      args: 
        - WEB_ENVIRONMENT=local
    ports:
      - "8081:80"
    depends_on:
      - api