version: '3.1'

services:
  api:
    image: 997143340873.dkr.ecr.eu-west-3.amazonaws.com/brbad-api:$CI_PIPELINE_IID
    container_name: api
    ports:
      - "3000:3000"
    networks:
      - brbad-network

  web:
    image: 997143340873.dkr.ecr.eu-west-3.amazonaws.com/brbad-web:$CI_PIPELINE_IID
    container_name: web
    ports:
      - "80:80"
    networks:
      - brbad-network
    environment: 
      - WEB_ENVIRONMENT=$WEB_ENVIRONMENT
    links:
      - api
       
networks:
  brbad-network:
    driver: bridge
    name: brbad-production-network